site_name: OpenFlightPlan Docs
site_url: https://docs.openflightplan.io
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Using the App: using-the-app.md
  - Flight Parameters: flight-parameters.md
  - Mobile Optimization: mobile.md
  - Developer Guide: developer-guide.md
  - Contributing: CONTRIBUTING.md
  - License: license.md
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: light blue
  font:
    text: "Open Sans"
    code: "Fira Code"
  logo: assets/logo.png
  favicon: assets/favicon.ico
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mostrager/mobile-flight-planner
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/michaelostrager
