site_name: OpenFlightPlan Docs
site_url: https://mostrager.github.io/mobile-flight-planner/
repo_url: https://github.com/mostrager/mobile-flight-planner
repo_name: GitHub
theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: light blue
  font:
    text: Roboto
    code: Roboto Mono
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Using the App: using-the-app.md
  - Mobile Access: mobile.md
  - Developer Guide: developer-guide.md
  - License: license.md
